### ISSUE TITLE
feature request: offer install as dependency or devDependency

### ISSUE THREAD

**Issue by capaj** [moshfeu/auto-npm-install#1]
thanks for creating this package. It doesn't give me the command, but it's probably just some small bug.

I'd like to as for a feature-instead of providing a sinlge command-could you provide two?

One for dependency, second for devDependecny. Cheers.

**Comment by capaj** [comment]
it's probably because the regex doesn't work properly, for example when i break here:
![image](https://user-images.githubusercontent.com/1305378/49680033-82b5fe80-fa90-11e8-86f6-8bfdcb5ab292.png)

I get this:

```js
/^import (.*) from ['|"]+([^./]{0,})+['|"];$/.  exec(text)
null
text
"import { GraphQLObjectType } from 'graphql'"
packageName
""
```

packageName comes back empty

**Comment by moshfeu** [comment]
Thanks for your issue! I see that you already fork it, you can PR this too :)
Or I will do it soon.

I think the second comment is meant to #2 , right?
